services:
  httpbin-mod_trace_context:
    image: kennethreitz/httpbin
    container_name: httpbin-mod_trace_context
    ports:
      - "7999:80"

  apache-mod_trace_context:
    build: .
    image: apache-mod_trace_context:latest
    container_name: apache-mod_trace_context
    depends_on:
      - httpbin-mod_trace_context
    ports:
      - "8443:8443"
    volumes:
      - ./examples/trace-proxy.httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
