ServerRoot "/usr/local/apache2"
ServerName localhost

PidFile "/usr/local/apache2/logs/httpd.pid"

User daemon
Group daemon

Listen 8080

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule headers_module modules/mod_headers.so
LoadModule unique_id_module modules/mod_unique_id.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule trace_context_module modules/mod_trace_context.so

ErrorLog /proc/self/fd/2
LogLevel error trace_context:trace7
LogFormat "%h %l %u %t \"%r\" %>s %b unique_id=%{UNIQUE_ID}e trace=%{trace-id}^TC parent=%{parent-id}^TC sampled=%{sampled}^TC traceparent=\"%{traceparent}^TC\" tracestate=\"%{tracestate}^TC\"" trace-context
CustomLog /proc/self/fd/1 trace-context

<VirtualHost *:8080>
    TraceContext On
    TraceContextTracestateMemberName apache-proxy

    TraceContextRequestHeaders both
    TraceContextResponseHeaders both

    #TraceContextSampleAllowExpr none
    #TraceContextSampleAllowExpr all
    TraceContextSampleAllowExpr "%{req:X-Test} == 'true'"

    #TraceContextSampleExpr none
    #TraceContextSampleExpr all
    TraceContextSampleExpr "%{req:X-Test-1} == 'true'"

    #TraceContextContinueTraceAllowExpr none
    #TraceContextContinueTraceAllowExpr all
    TraceContextContinueTraceAllowExpr "%{req:X-Test} == 'true'"

    RequestHeader set X-Unique-ID %{UNIQUE_ID}e
    Header set X-Unique-ID %{UNIQUE_ID}e

    ProxyPreserveHost On
    ProxyPass / http://httpbin-mod_trace_context:80/
    ProxyPassReverse / http://httpbin-mod_trace_context:80/
</VirtualHost>
