################################################################################
# DISCLAIMER: This configuration file is intended for DEVELOPMENT and TESTING
# purposes only. DO NOT use this configuration in production environments.
################################################################################

ServerRoot "/usr/local/apache2"
ServerName localhost

PidFile "/usr/local/apache2/logs/httpd.pid"

User daemon
Group daemon

Listen 8443 https

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule headers_module modules/mod_headers.so
LoadModule unique_id_module modules/mod_unique_id.so
LoadModule ssl_module modules/mod_ssl.so
LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule trace_context_module modules/mod_trace_context.so

ErrorLog /proc/self/fd/2
LogLevel error trace_context:trace7
LogFormat "%h %l %u %t \"%r\" %>s %b unique_id=%{UNIQUE_ID}e unique_id_orig=%{UNIQUE_ID_ORIG}e trace=%{tc-trace-id}e parent=%{tc-parent-id}e sampled=%{tc-sampled}e traceparent=\"%{tc-traceparent}e\" tracestate=\"%{tc-tracestate}e\"" trace-context
CustomLog /proc/self/fd/1 trace-context

SSLRandomSeed startup builtin
SSLRandomSeed connect builtin
SSLSessionCache "shmcb:/usr/local/apache2/logs/ssl_scache(512000)"

<VirtualHost *:8443>
    SSLEngine on
    SSLCertificateFile "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    SSLCertificateKeyFile "/etc/ssl/private/ssl-cert-snakeoil.key"
    TraceContext On
    TraceContextTracestateMemberName apache-proxy

    TraceContextRequestHeaders both
    TraceContextResponseHeaders both

    #TraceContextSampleAllowExpr none
    #TraceContextSampleAllowExpr all
    TraceContextSampleAllowExpr "%{req:X-TraceContextSampleAllowExpr} == 'true'"

    #TraceContextSampleExpr none
    #TraceContextSampleExpr all
    TraceContextSampleExpr "%{req:X-TraceContextSampleExpr} == 'true'"

    #TraceContextContinueTraceAllowExpr none
    #TraceContextContinueTraceAllowExpr all
    TraceContextContinueTraceAllowExpr "%{req:X-TraceContextContinueTraceAllowExpr} == 'true'"

    TraceContextReplaceUniqueID off
    #TraceContextReplaceUniqueID trace-id
    #TraceContextReplaceUniqueID parent-id
    #TraceContextReplaceUniqueID both
    #TraceContextReplaceUniqueID on

    RequestHeader set X-TC-Sampled %{tc-sampled}e
    Header set X-TC-Sampled %{tc-sampled}e

    RequestHeader set X-TC-Trace-ID %{tc-trace-id}e
    Header set X-TC-Trace-ID %{tc-trace-id}e

    RequestHeader set X-TC-Parent-ID %{tc-parent-id}e
    Header set X-TC-Parent-ID %{tc-parent-id}e

    RequestHeader set X-Unique-ID %{UNIQUE_ID}e
    Header set X-Unique-ID %{UNIQUE_ID}e

    RequestHeader set X-Unique-ID-Orig %{UNIQUE_ID_ORIG}e
    Header set X-Unique-ID-Orig %{UNIQUE_ID_ORIG}e

    ProxyPass        / http://httpbin-mod_trace_context:80/
    ProxyPassReverse / http://httpbin-mod_trace_context:80/
</VirtualHost>
